#!/usr/bin/env bash

IMG="/home/kwqcheii/source/kernel/img/bullseye.img.bak"
# IMG="/home/kwqcheii/source/kernel/img/bookworm.img.bak"



qemu-system-x86_64 \
        -cpu host \
        -enable-kvm \
        -smp 4 \
        -kernel "$1" \
        -append "root=/dev/vda console=ttyS0 earlyprintk=serial net.ifnames=0 panic_on_warn=0 nokaslr" \
        -blockdev file,node-name=f1,filename="$IMG" \
        -device virtio-blk,drive=f1 \
        -net user,host=10.0.2.10,hostfwd=tcp::9999-:22 \
        -net nic,model=e1000 \
        -m 4G \
        -nographic \
        -s \
        "$@"
