#!/usr/bin/env bash

mkfifo mytest

kitty @ goto-layout horizontal

if [[ -v SSH_TTY ]]; then
  SSH_IP=$(echo "$SSH_CONNECTION" | awk '{print $3 }')
  kitty @ launch ssh -t "$USER@$SSH_IP" "cd $PWD; echo \$$ > mytest; exec $1"
else
  kitty @ launch --cwd=current -- bash -c "echo \$$ > mytest; exec $1"
fi

CLD_PID=$(cat mytest)
rm mytest
waitpid "$CLD_PID"
